const CommentsTypes = {
  FETCH_COMMENTS_STATRS: 'FETCH_COMMENTS_STARTS',
  FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
  FETCH_COMMENTS_FAILURE: 'FETCH_COMMENTS_FAILYRE',
};

export default CommentsTypes;
