const UsersTypes = {
  FETCH_USERS_START: 'FETCH_USERS_START',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
  SET_TOTAL_USERS: 'SET_TOTAL_USERS',
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_ROWS_PERPAGE: 'SET_ROWS_PERPAGE',
  LOAD_MORE_USERS: 'LOAD_MORE_DATA',
  LOAD_MORE_USERS_SUCCESS: 'LOAD_MORE_USERS_SUCCESS',
  SEARCH_FOR_SPECIFIC_USER: 'SEARCH_FOR_SPECIFIC_USER',
};

export default UsersTypes;
